/* Launch Party Users */
/* Password is KnodaVip */
insert into users (email, encrypted_password, sign_in_count, created_at, updated_at,admin, username,notifications,points, streak) values ('sean.kosednar@gmail.com','$2a$10$TsZZGJZQWueQEzUkCAlo7OjQoEBZ1sBRFa4ZWUgVbsuaZuAGzQ9gC',0, now(), now(), FALSE, 'Sean', TRUE, 0, 0);
insert into users (email, encrypted_password, sign_in_count, created_at, updated_at,admin, username,notifications,points, streak) values ('Msherwood.design@gmail.com','$2a$10$TsZZGJZQWueQEzUkCAlo7OjQoEBZ1sBRFa4ZWUgVbsuaZuAGzQ9gC',0, now(), now(), FALSE, 'Marysherwood', TRUE, 0, 0);
insert into users (email, encrypted_password, sign_in_count, created_at, updated_at,admin, username,notifications,points, streak) values ('ppark89@gmail.com','$2a$10$TsZZGJZQWueQEzUkCAlo7OjQoEBZ1sBRFa4ZWUgVbsuaZuAGzQ9gC',0, now(), now(), FALSE, 'ppark', TRUE, 0, 0);
insert into users (email, encrypted_password, sign_in_count, created_at, updated_at,admin, username,notifications,points, streak) values ('adam.chura@gmail.com','$2a$10$TsZZGJZQWueQEzUkCAlo7OjQoEBZ1sBRFa4ZWUgVbsuaZuAGzQ9gC',0, now(), now(), FALSE, 'Adamchura', TRUE, 0, 0);
insert into users (username, email, encrypted_password, sign_in_count, created_at, updated_at,admin,notifications,points, streak) values ('A','aheuermann@gmail.com','$2a$10$TsZZGJZQWueQEzUkCAlo7OjQoEBZ1sBRFa4ZWUgVbsuaZuAGzQ9gC',0, now(), now(), FALSE, TRUE, 0, 0);
insert into users (username, email, encrypted_password, sign_in_count, created_at, updated_at,admin,notifications,points, streak) values ('Arynnnease','arynnnease@yahoo.com','$2a$10$TsZZGJZQWueQEzUkCAlo7OjQoEBZ1sBRFa4ZWUgVbsuaZuAGzQ9gC',0, now(), now(), FALSE, TRUE, 0, 0);
insert into users (username, email, encrypted_password, sign_in_count, created_at, updated_at,admin,notifications,points, streak) values ('itsjenno','jenn.r.ong@gmail.com','$2a$10$TsZZGJZQWueQEzUkCAlo7OjQoEBZ1sBRFa4ZWUgVbsuaZuAGzQ9gC',0, now(), now(), FALSE, TRUE, 0, 0);
insert into users (username, email, encrypted_password, sign_in_count, created_at, updated_at,admin,notifications,points, streak) values ('J','juliedumovich@gmail.com','$2a$10$TsZZGJZQWueQEzUkCAlo7OjQoEBZ1sBRFa4ZWUgVbsuaZuAGzQ9gC',0, now(), now(), FALSE, TRUE, 0, 0);
insert into users (username, email, encrypted_password, sign_in_count, created_at, updated_at,admin,notifications,points, streak) values ('ecnal15','ecnal15@gmail.com','$2a$10$TsZZGJZQWueQEzUkCAlo7OjQoEBZ1sBRFa4ZWUgVbsuaZuAGzQ9gC',0, now(), now(), FALSE, TRUE, 0, 0);
insert into users (username, email, encrypted_password, sign_in_count, created_at, updated_at,admin,notifications,points, streak) values ('Shawnquesnell','squesnell@sportingkc.com','$2a$10$TsZZGJZQWueQEzUkCAlo7OjQoEBZ1sBRFa4ZWUgVbsuaZuAGzQ9gC',0, now(), now(), FALSE, TRUE, 0, 0);
insert into users (username, email, encrypted_password, sign_in_count, created_at, updated_at,admin,notifications,points, streak) values ('Z','joez@tax-hero.com','$2a$10$TsZZGJZQWueQEzUkCAlo7OjQoEBZ1sBRFa4ZWUgVbsuaZuAGzQ9gC',0, now(), now(), FALSE, TRUE, 0, 0);
insert into users (username, email, encrypted_password, sign_in_count, created_at, updated_at,admin,notifications,points, streak) values ('JSpirKC','josephspirk@yahoo.com','$2a$10$TsZZGJZQWueQEzUkCAlo7OjQoEBZ1sBRFa4ZWUgVbsuaZuAGzQ9gC',0, now(), now(), FALSE, TRUE, 0, 0);
insert into users (username, email, encrypted_password, sign_in_count, created_at, updated_at,admin,notifications,points, streak) values ('Bbuckley123','bbuckley123@gmail.com','$2a$10$TsZZGJZQWueQEzUkCAlo7OjQoEBZ1sBRFa4ZWUgVbsuaZuAGzQ9gC',0, now(), now(), FALSE, TRUE, 0, 0);
insert into users (username, email, encrypted_password, sign_in_count, created_at, updated_at,admin,notifications,points, streak) values ('david','david.snodgrass@gmail.com','$2a$10$TsZZGJZQWueQEzUkCAlo7OjQoEBZ1sBRFa4ZWUgVbsuaZuAGzQ9gC',0, now(), now(), FALSE, TRUE, 0, 0);
insert into users (username, email, encrypted_password, sign_in_count, created_at, updated_at,admin,notifications,points, streak) values ('ElkanahReed','elkanahreed@me.com','$2a$10$TsZZGJZQWueQEzUkCAlo7OjQoEBZ1sBRFa4ZWUgVbsuaZuAGzQ9gC',0, now(), now(), FALSE, TRUE, 0, 0);
insert into users (username, email, encrypted_password, sign_in_count, created_at, updated_at,admin,notifications,points, streak) values ('Tam','tam@galleonlabs.com','$2a$10$TsZZGJZQWueQEzUkCAlo7OjQoEBZ1sBRFa4ZWUgVbsuaZuAGzQ9gC',0, now(), now(), FALSE, TRUE, 0, 0);
insert into users (username, email, encrypted_password, sign_in_count, created_at, updated_at,admin,notifications,points, streak) values ('Kyle','kyle_morrissey@hotmail.com','$2a$10$TsZZGJZQWueQEzUkCAlo7OjQoEBZ1sBRFa4ZWUgVbsuaZuAGzQ9gC',0, now(), now(), FALSE, TRUE, 0, 0);
insert into users (username, email, encrypted_password, sign_in_count, created_at, updated_at,admin,notifications,points, streak) values ('RachelDoull','racheldoull@gmail.com','$2a$10$TsZZGJZQWueQEzUkCAlo7OjQoEBZ1sBRFa4ZWUgVbsuaZuAGzQ9gC',0, now(), now(), FALSE, TRUE, 0, 0);
insert into users (username, email, encrypted_password, sign_in_count, created_at, updated_at,admin,notifications,points, streak) values ('TJ','tjr1486@gmail.com','$2a$10$TsZZGJZQWueQEzUkCAlo7OjQoEBZ1sBRFa4ZWUgVbsuaZuAGzQ9gC',0, now(), now(), FALSE, TRUE, 0, 0);
insert into users (username, email, encrypted_password, sign_in_count, created_at, updated_at,admin,notifications,points, streak) values ('MrNaylorCEO','baylor135@yahoo.com','$2a$10$TsZZGJZQWueQEzUkCAlo7OjQoEBZ1sBRFa4ZWUgVbsuaZuAGzQ9gC',0, now(), now(), FALSE, TRUE, 0, 0);
insert into users (username, email, encrypted_password, sign_in_count, created_at, updated_at,admin,notifications,points, streak) values ('Katieburton','kmccaffrey@gmail.com','$2a$10$TsZZGJZQWueQEzUkCAlo7OjQoEBZ1sBRFa4ZWUgVbsuaZuAGzQ9gC',0, now(), now(), FALSE, TRUE, 0, 0);
insert into users (username, email, encrypted_password, sign_in_count, created_at, updated_at,admin,notifications,points, streak) values ('Walrus','davidberman@gmail.com','$2a$10$TsZZGJZQWueQEzUkCAlo7OjQoEBZ1sBRFa4ZWUgVbsuaZuAGzQ9gC',0, now(), now(), FALSE, TRUE, 0, 0);
insert into users (username, email, encrypted_password, sign_in_count, created_at, updated_at,admin,notifications,points, streak) values ('TheChadKC','reynolds.chad@gmail.com','$2a$10$TsZZGJZQWueQEzUkCAlo7OjQoEBZ1sBRFa4ZWUgVbsuaZuAGzQ9gC',0, now(), now(), FALSE, TRUE, 0, 0);
insert into users (username, email, encrypted_password, sign_in_count, created_at, updated_at,admin,notifications,points, streak) values ('Ravipatel','rpmd30@gmail.com','$2a$10$TsZZGJZQWueQEzUkCAlo7OjQoEBZ1sBRFa4ZWUgVbsuaZuAGzQ9gC',0, now(), now(), FALSE, TRUE, 0, 0);
insert into users (username, email, encrypted_password, sign_in_count, created_at, updated_at,admin,notifications,points, streak) values ('Mormon','coachvicki1222@aol.com','$2a$10$TsZZGJZQWueQEzUkCAlo7OjQoEBZ1sBRFa4ZWUgVbsuaZuAGzQ9gC',0, now(), now(), FALSE, TRUE, 0, 0);
insert into users (username, email, encrypted_password, sign_in_count, created_at, updated_at,admin,notifications,points, streak) values ('Jyhwkfn82','jyhwkfn82@yahoo.com','$2a$10$TsZZGJZQWueQEzUkCAlo7OjQoEBZ1sBRFa4ZWUgVbsuaZuAGzQ9gC',0, now(), now(), FALSE, TRUE, 0, 0);
insert into users (username, email, encrypted_password, sign_in_count, created_at, updated_at,admin,notifications,points, streak) values ('Snow','remy65@hotmail.com','$2a$10$TsZZGJZQWueQEzUkCAlo7OjQoEBZ1sBRFa4ZWUgVbsuaZuAGzQ9gC',0, now(), now(), FALSE, TRUE, 0, 0);
insert into users (username, email, encrypted_password, sign_in_count, created_at, updated_at,admin,notifications,points, streak) values ('Tammy','woodstl@umkc.edu','$2a$10$TsZZGJZQWueQEzUkCAlo7OjQoEBZ1sBRFa4ZWUgVbsuaZuAGzQ9gC',0, now(), now(), FALSE, TRUE, 0, 0);
insert into users (username, email, encrypted_password, sign_in_count, created_at, updated_at,admin,notifications,points, streak) values ('LogmanScott','heartlandrlloghm@aol.com','$2a$10$TsZZGJZQWueQEzUkCAlo7OjQoEBZ1sBRFa4ZWUgVbsuaZuAGzQ9gC',0, now(), now(), FALSE, TRUE, 0, 0);
insert into users (username, email, encrypted_password, sign_in_count, created_at, updated_at,admin,notifications,points, streak) values ('LindsayKSU','lindsay.leiler@gmail.com','$2a$10$TsZZGJZQWueQEzUkCAlo7OjQoEBZ1sBRFa4ZWUgVbsuaZuAGzQ9gC',0, now(), now(), FALSE, TRUE, 0, 0);
insert into users (username, email, encrypted_password, sign_in_count, created_at, updated_at,admin,notifications,points, streak) values ('Sarah','sadoull@gmail.com','$2a$10$TsZZGJZQWueQEzUkCAlo7OjQoEBZ1sBRFa4ZWUgVbsuaZuAGzQ9gC',0, now(), now(), FALSE, TRUE, 0, 0);
insert into users (username, email, encrypted_password, sign_in_count, created_at, updated_at,admin,notifications,points, streak) values ('Superrad','rebecca.gubbels@gmail.com','$2a$10$TsZZGJZQWueQEzUkCAlo7OjQoEBZ1sBRFa4ZWUgVbsuaZuAGzQ9gC',0, now(), now(), FALSE, TRUE, 0, 0);
insert into users (username, email, encrypted_password, sign_in_count, created_at, updated_at,admin,notifications,points, streak) values ('Jrwahova19','jrockp19@yahoo.com','$2a$10$TsZZGJZQWueQEzUkCAlo7OjQoEBZ1sBRFa4ZWUgVbsuaZuAGzQ9gC',0, now(), now(), FALSE, TRUE, 0, 0);
insert into users (username, email, encrypted_password, sign_in_count, created_at, updated_at,admin,notifications,points, streak) values ('Cvallee','cvallee2012@gmail.com','$2a$10$TsZZGJZQWueQEzUkCAlo7OjQoEBZ1sBRFa4ZWUgVbsuaZuAGzQ9gC',0, now(), now(), FALSE, TRUE, 0, 0);

/* Beta Testers */
/* Password is whatever it was in test */
insert into users (username, email, encrypted_password, sign_in_count, created_at, updated_at,admin,notifications,points, streak) values ('emkristen','emkristen13@gmail.com','$2a$10$k/vhXbeDDQmeyb.pTgKXbOoSxQ32wlSkZb.YkgHo0EndvBAMNrZbW',0, now(), now(), FALSE, TRUE, 0, 0);
insert into users (username, email, encrypted_password, sign_in_count, created_at, updated_at,admin,notifications,points, streak) values ('joeynewcastle','joseph.newcastle@gmail.com','$2a$10$7hvsxKTWAyWjiIBddiNSuelIj50CIQbUrDkewNJ0E7hkn1FRLlYku',0, now(), now(), FALSE, TRUE, 0, 0);
insert into users (username, email, encrypted_password, sign_in_count, created_at, updated_at,admin,notifications,points, streak) values ('shurd','sarafhurd@gmail.com','$2a$10$FPQHTlGNTQYtgigdjEyRWeL//2c/z.dIjI6Cx6FCHM5d/L6HFqswm',0, now(), now(), FALSE, TRUE, 0, 0);
insert into users (username, email, encrypted_password, sign_in_count, created_at, updated_at,admin,notifications,points, streak) values ('holseff','joelmferguson@gmail.com','$2a$10$N1kJNwPMi3dDTghZZD77GeIQ4pn9v2c.N6ojd/Fhpf3J5n.mdWJBm',0, now(), now(), FALSE, TRUE, 0, 0);
insert into users (username, email, encrypted_password, sign_in_count, created_at, updated_at,admin,notifications,points, streak) values ('jshack','shackelfordjd@umkc.com','$2a$10$f7EdYuPiLW3Z7ITs2V2ZPOy97gQj3xKCwZedsAwkAIXTiUVA/pAEq',0, now(), now(), FALSE, TRUE, 0, 0);
insert into users (username, email, encrypted_password, sign_in_count, created_at, updated_at,admin,notifications,points, streak) values ('albert','ahtong@gmail.com','$2a$10$F45N6qIEDJlcaNU33vFZV.Jrt9cFtES.Et59jZkAde8z4G5CUqUYK',0, now(), now(), FALSE, TRUE, 0, 0);
insert into users (username, email, encrypted_password, sign_in_count, created_at, updated_at,admin,notifications,points, streak) values ('Dave','davidborgerding@gmail.com','$2a$10$IXFkkK6OhIYo8fs7/iZsOeG1HdXasC08kFaGCbrpSF/gbmuED7dje',0, now(), now(), FALSE, TRUE, 0, 0);
insert into users (username, email, encrypted_password, sign_in_count, created_at, updated_at,admin,notifications,points, streak) values ('ThomasK','tgkershisnik@aol.com','$2a$10$v8tFDUZZII52F/NPTkfsuOqwTrKO8dnziw5tKTDSjZpW2HfFJVE3G',0, now(), now(), FALSE, TRUE, 0, 0);
insert into users (username, email, encrypted_password, sign_in_count, created_at, updated_at,admin,notifications,points, streak) values ('mishi_lea22','iles_michelle@yahoo.com','$2a$10$pMpXOdNdlhwR1tZkTv/8sO8hX6ZiNHhNOIvoY5Ot77MHhDwjLFxcm',0, now(), now(), FALSE, TRUE, 0, 0);
insert into users (username, email, encrypted_password, sign_in_count, created_at, updated_at,admin,notifications,points, streak) values ('rockdmb','aj.kinsella@gmail.com','$2a$10$DyXNm/9vDaAukOb5UOaNcO0Po5qniTk2NgJDKqAcB/PyOSuSIFoue',0, now(), now(), FALSE, TRUE, 0, 0);
insert into users (username, email, encrypted_password, sign_in_count, created_at, updated_at,admin,notifications,points, streak) values ('akgarcia331','andrea.k.garcia@gmail.com','$2a$10$T2OaQwMvpwe66ZFzY/xKl.Xe91cfo5jrI7/9EdUv0veHDkzyYevoq',0, now(), now(), FALSE, TRUE, 0, 0);
insert into users (username, email, encrypted_password, sign_in_count, created_at, updated_at,admin,notifications,points, streak) values ('ryan','ryan@fiveelms.com','$2a$10$EZ9UQClQt7nk6bLuUSEUX.u2JPNdSeXGFLvtaTjRKcXd/HSGSE0hK',0, now(), now(), FALSE, TRUE, 0, 0);
insert into users (username, email, encrypted_password, sign_in_count, created_at, updated_at,admin,notifications,points, streak) values ('blakestrobel','blake.strobel@gmail.com','$2a$10$vOYzWplU3gh4ZFW2JdDWpO4ka61uLhZcG5vAVx6WUwqkQhHwlckp.',0, now(), now(), FALSE, TRUE, 0, 0);
insert into users (username, email, encrypted_password, sign_in_count, created_at, updated_at,admin,notifications,points, streak) values ('Drew','drew.warren.rogers@gmail.com','$2a$10$r3ohsA7uxXrAf4ecvmSrleA5BEZpn2Ira1o6468yOBx2IX/cATNvW',0, now(), now(), FALSE, TRUE, 0, 0);
insert into users (username, email, encrypted_password, sign_in_count, created_at, updated_at,admin,notifications,points, streak) values ('edblythe','eddie.army83@gmail.com','$2a$10$y2rdEz3e36X8PUHtD0EEj.6E109LflAk2PpMFDZhHKb.Hodj.yfPm',0, now(), now(), FALSE, TRUE, 0, 0);
insert into users (username, email, encrypted_password, sign_in_count, created_at, updated_at,admin,notifications,points, streak) values ('Kate','katefavrow@gmail.com','$2a$10$FRPFulN9EKXeWtmRrBgNbuVpDaxoIMAW7T7aAuJ2whV8cleiyosLW',0, now(), now(), FALSE, TRUE, 0, 0);
insert into users (username, email, encrypted_password, sign_in_count, created_at, updated_at,admin,notifications,points, streak) values ('thillsman','tyler.hillsman@gmail.com','$2a$10$/ILaqPv3mlt5jD9epbVktuPq8kFTiWyDtD4SXBJZFAA5snMjuk69u',0, now(), now(), FALSE, TRUE, 0, 0);
insert into users (username, email, encrypted_password, sign_in_count, created_at, updated_at,admin,notifications,points, streak) values ('joy','sarah.joy9@gmail.com','$2a$10$LZQP5wdCQP29JDftrYE22eaACWt4BlcneICpHaTUGUzu36/FmGNXq',0, now(), now(), FALSE, TRUE, 0, 0);
insert into users (username, email, encrypted_password, sign_in_count, created_at, updated_at,admin,notifications,points, streak) values ('cfish415','cfisher@cobrapps.com','$2a$10$2QuzId2/QgvKvqZNm5buPOt4ZslIJsigLoXA5kYv6qOjAx.0Z7f.e',0, now(), now(), FALSE, TRUE, 0, 0);
insert into users (username, email, encrypted_password, sign_in_count, created_at, updated_at,admin,notifications,points, streak) values ('jcnthe1st','jerrynevins@gmail.com','$2a$10$xExcNp82y4jk1wrqoYH65OsVL6xBUWoNoW9HmZAJe/A74wzCBkfpi',0, now(), now(), FALSE, TRUE, 0, 0);
insert into users (username, email, encrypted_password, sign_in_count, created_at, updated_at,admin,notifications,points, streak) values ('joedavismedia','joedavis34@gmail.com','$2a$10$prPDm2nWZcs14PNGAi1AheUbHiZkPLiNjQ.p/P6n.QvWvyznNQUd6',0, now(), now(), FALSE, TRUE, 0, 0);
insert into users (username, email, encrypted_password, sign_in_count, created_at, updated_at,admin,notifications,points, streak) values ('dtemple1985','dtemple1985@yahoo.com','$2a$10$dKD8Ew5BjRMrN2pTTnQ9S.zTzMJ/TGHhREEA44fCcGlhAZZk/ZuVS',0, now(), now(), FALSE, TRUE, 0, 0);
insert into users (username, email, encrypted_password, sign_in_count, created_at, updated_at,admin,notifications,points, streak) values ('mase57','alana33@gmail.com','$2a$10$TeSKelhxFLmrrVJSW23TveheFVf/OzTCSXpTR7OE8qmCHU1w03aOW',0, now(), now(), FALSE, TRUE, 0, 0);
insert into users (username, email, encrypted_password, sign_in_count, created_at, updated_at,admin,notifications,points, streak) values ('DaveBorchardt','dave.borchardt@yahoo.com','$2a$10$uORHK7ydATcS6RBHf/1wnOzRkoLvUBVc/9JhA0jO3c4pcKUvuJraK',0, now(), now(), FALSE, TRUE, 0, 0);
insert into users (username, email, encrypted_password, sign_in_count, created_at, updated_at,admin,notifications,points, streak) values ('MichelleMajo','michellemajerle@gmail.com','$2a$10$lSP.nu17/MMUf9LFoJCNU.Wrui8F52IIPM7OAV4UgQstHmQbwfM02',0, now(), now(), FALSE, TRUE, 0, 0);
insert into users (username, email, encrypted_password, sign_in_count, created_at, updated_at,admin,notifications,points, streak) values ('kevin','kevinfryer@overlap.com','$2a$10$Q2K7y3smD/SBLPA9R8QSbu/snupJZO4Li4SOM/bA/queHZV5m5EQq',0, now(), now(), FALSE, TRUE, 0, 0);
insert into users (username, email, encrypted_password, sign_in_count, created_at, updated_at,admin,notifications,points, streak) values ('alana','alana.rhone@washburn.edu','$2a$10$Wjj/V5A0C1/Yf8d8oDW6oekqDunAaTQdOZBqykV0YCU7UXPzSY7Pa',0, now(), now(), FALSE, TRUE, 0, 0);
insert into users (username, email, encrypted_password, sign_in_count, created_at, updated_at,admin,notifications,points, streak) values ('cfisher','loui415@gmail.com','$2a$10$I3cKOsrRbqb5hX1GhtEx5OCKm7nzTE3A0oHQqJ83/xWOD7V9nfR.O',0, now(), now(), FALSE, TRUE, 0, 0);
insert into users (username, email, encrypted_password, sign_in_count, created_at, updated_at,admin,notifications,points, streak) values ('kflexman','kallie.flexman@gmail.com','$2a$10$HR3cHnNAjNwgusfHW6PKHOebCoT70.1hLOsXGasyxrWPRlMcIVEYK',0, now(), now(), FALSE, TRUE, 0, 0);
insert into users (username, email, encrypted_password, sign_in_count, created_at, updated_at,admin,notifications,points, streak) values ('TCalia','caliathomas@gmail.com','$2a$10$DSHR.OSZGddgNZkqtQeyaOtvBM81DJy/xi3ueQvsOASFfRLywMiCa',0, now(), now(), FALSE, TRUE, 0, 0);
insert into users (username, email, encrypted_password, sign_in_count, created_at, updated_at,admin,notifications,points, streak) values ('royalbb','kylevena11@gmail.com','$2a$10$0YCp7mJbDObCRRknALyRKehE27.T1Pzh.cKO7wduUoXhs2JnDg/5e',0, now(), now(), FALSE, TRUE, 0, 0);
insert into users (username, email, encrypted_password, sign_in_count, created_at, updated_at,admin,notifications,points, streak) values ('EmperorAdam','adam.n.england@gmail.com','$2a$10$9Ft3BJyn4wvjBgred8zX1.F.r5TCKJq3jEtR054OdgJvQLCm3N4BS',0, now(), now(), FALSE, TRUE, 0, 0);
insert into users (username, email, encrypted_password, sign_in_count, created_at, updated_at,admin,notifications,points, streak) values ('Michelle','schneider.chelle@gmail.com','$2a$10$ap5OCHvrSzFthAxnef5VC.G450MXetuXVU/4IC.9kfuSa2AfRW9J.',0, now(), now(), FALSE, TRUE, 0, 0);
insert into users (username, email, encrypted_password, sign_in_count, created_at, updated_at,admin,notifications,points, streak) values ('roastbeef','cmonetti@gmail.com','$2a$10$eCt9vUKSJ9R6lm9GdJeMdOciJE0L9I6QVw9iSsMsHx5P/G8qKt.a6',0, now(), now(), FALSE, TRUE, 0, 0);
insert into users (username, email, encrypted_password, sign_in_count, created_at, updated_at,admin,notifications,points, streak) values ('mitchfav','mitchfav@ku.edu','$2a$10$wEhIdkekvKWIl8gUBk2OzOd35s5bwEVqdvFP9gt8093Iu3MlwOmAi',0, now(), now(), FALSE, TRUE, 0, 0);

  /* To run psql -d knoda_development -f ~/code/knoda/db/addLaunchUsers.sql */